import { readFileSync } from 'fs';
import { join } from 'path';

export function prerender() {
  try {
    // Read the routes manifest generated by the fetch-data script
    const routesPath = join(process.cwd(), 'public', 'data', 'routes.json');
    const routes = JSON.parse(readFileSync(routesPath, 'utf-8'));
    return routes;
  } catch (error) {
    console.warn('Could not load prerender routes, falling back to basic routes:', error);
    return ['/'];
  }
}